name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Test, Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test -Psecret=%SECRET_MESSAGE% --stacktrace
      - name: Build debug APK
        run: bash ./gradlew assembleDebug -Psecret=%SECRET_MESSAGE% --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk